/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import javax.swing.JPanel;

/**
 *
 * @author Purvi
 */
public class HomeFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomeFrame.class.getName());

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
        
        showPanel(new Dashboardpanel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBar = new javax.swing.JPanel();
        dashboardBtn = new javax.swing.JButton();
        issueBtn = new javax.swing.JButton();
        registerationbtn = new javax.swing.JButton();
        loginbtn = new javax.swing.JButton();
        bookmanagebtn = new javax.swing.JButton();
        memberdetailbtn = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sideBar.setBackground(new java.awt.Color(51, 102, 255));

        dashboardBtn.setText("Dashboard");
        dashboardBtn.addActionListener(this::dashboardBtnActionPerformed);

        issueBtn.setText("Issue Book");
        issueBtn.addActionListener(this::issueBtnActionPerformed);

        registerationbtn.setText("Registeration");
        registerationbtn.addActionListener(this::registerationbtnActionPerformed);

        loginbtn.setText("Login");
        loginbtn.addActionListener(this::loginbtnActionPerformed);

        bookmanagebtn.setText("Book Management");
        bookmanagebtn.addActionListener(this::bookmanagebtnActionPerformed);

        memberdetailbtn.setText("Member Details");
        memberdetailbtn.addActionListener(this::memberdetailbtnActionPerformed);

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dashboardBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(issueBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registerationbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookmanagebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(memberdetailbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(dashboardBtn)
                .addGap(35, 35, 35)
                .addComponent(issueBtn)
                .addGap(34, 34, 34)
                .addComponent(registerationbtn)
                .addGap(34, 34, 34)
                .addComponent(loginbtn)
                .addGap(35, 35, 35)
                .addComponent(bookmanagebtn)
                .addGap(38, 38, 38)
                .addComponent(memberdetailbtn)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1144, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void showPanel(JPanel panel) {
        
        contentPanel.removeAll();
        contentPanel.setLayout(new java.awt.BorderLayout());
        contentPanel.add(panel,java.awt.BorderLayout.CENTER);
        contentPanel.revalidate();
        contentPanel.repaint();
        
    }
    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        // TODO add your handling code here:
        showPanel(new Dashboardpanel());
    }//GEN-LAST:event_dashboardBtnActionPerformed

    private void issueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBtnActionPerformed
        // TODO add your handling code here:
        
        showPanel(new Issuep());
    }//GEN-LAST:event_issueBtnActionPerformed

    private void memberdetailbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberdetailbtnActionPerformed
        // TODO add your handling code here:
        showPanel(new Memberdetailsp());
    }//GEN-LAST:event_memberdetailbtnActionPerformed

    private void bookmanagebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookmanagebtnActionPerformed
        // TODO add your handling code here:
        
        new bookmanagementp();
    }//GEN-LAST:event_bookmanagebtnActionPerformed

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginbtnActionPerformed

    private void registerationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerationbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerationbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomeFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookmanagebtn;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JButton issueBtn;
    private javax.swing.JButton loginbtn;
    private javax.swing.JButton memberdetailbtn;
    private javax.swing.JButton registerationbtn;
    private javax.swing.JPanel sideBar;
    // End of variables declaration//GEN-END:variables
}
